# Parámetros para generador_datos
generador:
  n_activos: 100
  t_periodos: 10
  crecimiento: 0.03
  m_fondo: 30  # número de activos para el fondo sintético
  peso_maximo_fondo: 0.10  # peso máximo para el fondo sintético

# Parámetros para optimizador_fondo
optimizador:
  M: 30  # número máximo de activos
  P: 0.10  # peso máximo por activo
  max_intentos: 10  # número de intentos de optimización

# Rutas de archivos
rutas:
  rendimientos: "data_sintetica/activos_rendimientos.csv"
  fondo: "data_sintetica/fondo_evolucion.csv"
  resultados: "resultados" 